pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build Docker Image') {
      steps {
        dir('Practical-1') {
          sh 'docker build -t dockerized-ci-cd:latest -f Dockerfile .'
        }
      }
    }

    stage('Run Container') {
      steps {
        dir('Practical-1') {
          sh 'docker run --rm dockerized-ci-cd:latest | tee output.txt'
        }
      }
    }
  }

  post {
    always {
      archiveArtifacts artifacts: 'Practical-1/output.txt', fingerprint: true
    }
  }
}
