name: Docker Build and Run Practical-1

on:
  push:
    paths:
      - 'Practical-1/**'
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t dockerized-ci-cd:latest -f $GITHUB_WORKSPACE/Practical-1/Dockerfile $GITHUB_WORKSPACE/Practical-1


      - name: Run container and capture output
        working-directory: Practical-1
        run: docker run --rm dockerized-ci-cd:latest > output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: practical-1-output
          path: Practical-1/output.txt
