name: Dockerized App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t dockerized-ci-cd:latest .

      - name: Run container and save output
        run: |
          docker run --rm dockerized-ci-cd:latest | tee output.txt
          echo "Saved output to output.txt"

      - name: Upload output artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-output
          path: output.txt
