name: Practical-3 CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and start services with docker compose
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker compose -f Practical-3/docker-compose.yml up -d --build

      - name: Wait for health endpoint
        run: |
          set -e
          for i in {1..10}; do
            echo "Attempt $i: checking http://localhost:8080/health"
            if curl --fail http://localhost:8080/health; then
              echo "Health check succeeded!"
              exit 0
            fi
            sleep 3
          done
          echo "Health check failed"
          docker compose -f Practical-3/docker-compose.yml logs
          exit 1

      - name: Teardown compose
        if: always()
        run: docker compose -f Practical-3/docker-compose.yml down --rmi local

      - name: Push images to Docker Hub
        if: success()
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker push ${DOCKERHUB_USERNAME}/backend:latest
          docker push ${DOCKERHUB_USERNAME}/nginx:latest
